name: Release

on:
  push:
    branches: [ dev] # Only on push to dev because on push to main the release workflow runs the perf tests

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest # Build on Windows to ensure .NET Framework targets
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run build
        run: ./Build.ps1 -SkipTests
        shell: pwsh

      - name: Run performance tests
        run: ./RunPerfTests.ps1
        shell: pwsh
