name: PR Analysis InferSharp
on:
on:
  workflow_run:
    workflows: [ "PR Validation" ]
    branches: [ dev, main ]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Upload binaries artifact for InferSharp workflow
        uses: actions/download-artifact@v3
        with:
          name: bin-net6

      - name: Run Infer#      
        uses: microsoft/infersharpaction@v1.4
        id: runinfersharp
        with:
          binary-path: bin-net6

      - name: Upload SARIF output to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: infer-out/report.sarif
